package com.company.project.domain;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table person
 */
public class Person implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.Id
     *
     * @mbg.generated Tue Oct 02 21:45:37 CST 2018
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   人名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.personname
     *
     * @mbg.generated Tue Oct 02 21:45:37 CST 2018
     */
    private String personname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person
     *
     * @mbg.generated Tue Oct 02 21:45:37 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.Id
     *
     * @return the value of person.Id
     *
     * @mbg.generated Tue Oct 02 21:45:37 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.Id
     *
     * @param id the value for person.Id
     *
     * @mbg.generated Tue Oct 02 21:45:37 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.personname
     *
     * @return the value of person.personname
     *
     * @mbg.generated Tue Oct 02 21:45:37 CST 2018
     */
    public String getPersonname() {
        return personname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.personname
     *
     * @param personname the value for person.personname
     *
     * @mbg.generated Tue Oct 02 21:45:37 CST 2018
     */
    public void setPersonname(String personname) {
        this.personname = personname;
    }
}