package com.company.project.dao;

import com.company.project.domain.Person;
import com.company.project.domain.PersonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Oct 02 21:45:37 CST 2018
     */
    long countByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Oct 02 21:45:37 CST 2018
     */
    int deleteByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Oct 02 21:45:37 CST 2018
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("personname") String personname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Oct 02 21:45:37 CST 2018
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Oct 02 21:45:37 CST 2018
     */
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Oct 02 21:45:37 CST 2018
     */
    List<Person> selectByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Oct 02 21:45:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Oct 02 21:45:37 CST 2018
     */
    int updateByExample(@Param("record") Person record, @Param("example") PersonExample example);
}